### ISSUE TITLE
Hi! Maybe you want to combine forces ?

### ISSUE THREAD

**Issue by Jeremi360** [OneiroGames/OneiroNovel#1]
From what I read in this project README you making the very similar project to my [Rakugo](https://github.com/rakugoteam) / [vnkit](https://github.com/rakugoteam/VisualNovelKit).
So maybe you want to join my team ?

**Comment by DezlowNG** [comment]
Hello, my project not similar by Rakugo.
I'm using C# for logic and Ink for stories and I don't have in my plans to implement "Ren'Py, but in Godot".
I preferred Ren'Py code style, because it's simple and more readable (in my own engines I tried to create [own style](https://github.com/OneiroGames/TSOCA/blob/main/Assets/Scripts/main.lua#L48-L55), but it not readable as Ren'Py).
